In [1]:
#Example XGBRegression
import pandas as pd
import numpy as np
from numpy import mean
from numpy import std
import scipy
from sklearn.model_selection import GroupKFold
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from lineartree import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn import metrics
import matplotlib.pyplot as plt
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe

In [2]:
def rae(actual, predicted):
    actual = np.asarray(actual).reshape(-1,1)
    predicted = np.asarray(predicted).reshape(-1,1)
    numerator = np.sum(np.abs(predicted - actual))
    denominator = np.sum(np.abs(np.mean(actual) - actual))
    return numerator / denominator

In [3]:
def peak_eV_nm(peak_eV):
    peak_eV = np.asarray(peak_eV).reshape(-1,1)
    return 1239.84193/peak_eV

In [4]:
def FWHM_eV_nm(peak_eV,fwhm_eV):
    peak_eV = np.asarray(peak_eV).reshape(-1,1)
    fwhm_eV = np.asarray(fwhm_eV).reshape(-1,1)
    return  2*(1239.84193/(peak_eV-fwhm_eV/2) - 1239.84193/(peak_eV))

In [5]:
def L2_Reg(x1):    
    #Test Linear Regression on Train/Val set, 10-fold cross validation (Group splits), UV Peak, FWHM (eV), Normalized
    # load dataset into Pandas DataFrame (cleaned UV data)
    df = pd.read_csv('CdSe PL Train Val.csv')

    #normalize input and output data
    min_params = pd.Series([0, 0, 3, 200, 0, 400, 15, 1239.84193/620, 0.05], index =['Cd_mM', 'Se_mM', 'OA_Cd_ratio', 'T_reactor', 't_s','Peak_nm','FWHM_nm','Peak_eV','FWHM_eV'])
    max_params = pd.Series([50, 50, 150, 310, 600, 620, 80, 1239.84193/400, 0.4], index =['Cd_mM', 'Se_mM', 'OA_Cd_ratio', 'T_reactor', 't_s','Peak_nm','FWHM_nm','Peak_eV','FWHM_eV'])
    df[['Cd_mM', 'Se_mM', 'OA_Cd_ratio', 'T_reactor', 't_s','Peak_nm','FWHM_nm','Peak_eV','FWHM_eV']] = (df[['Cd_mM', 'Se_mM', 'OA_Cd_ratio', 'T_reactor', 't_s','Peak_nm','FWHM_nm','Peak_eV','FWHM_eV']] - min_params) / (max_params- min_params)

    X = df[['OA_Cd_ratio','T_reactor','Cd_mM','Se_mM','t_s']]
    X2 = df[['OA_Cd_ratio','T_reactor','Cd_mM','Se_mM','t_s','Peak_eV']]
    y = df['Peak_eV']
    z = df['FWHM_eV']
    group = df['Expt. No']

    regressor_peak = Ridge(alpha=x1)
    regressor_fwhm = Ridge(alpha=x1)
    regressor_cascade = Ridge(alpha=x1)

    gkf = GroupKFold(n_splits=10)
    matrix = np.zeros([10,13])
    matrix_fwhm = np.zeros([10,13])
    matrix_cascade = np.zeros([10,14])
    for i in range(0,1):
        j = 0
        for train_index, test_index in gkf.split(X, groups=group):
            #Separate out training and test sets
            X_train = X.iloc[train_index, :]
            X2_train = X2.iloc[train_index, :]
            y_train = y[train_index]
            z_train = z[train_index]
            X_test = X.iloc[test_index, :]
            y_test = y[test_index]
            z_test = z[test_index]

            #prediction for Peak
            regressor_peak.fit(X_train, y_train)
            y_pred = regressor_peak.predict(X_test)
            #prediction for FWHM (direct)
            regressor_fwhm.fit(X_train, z_train)
            y_pred_fwhm = regressor_fwhm.predict(X_test)
            #prediction for FWHM (cascade)
            regressor_cascade.fit(X2_train, z_train)
            X_test.insert(5, "Peak_eV", regressor_peak.predict(X_test), True)
            y_pred_cascade = regressor_cascade.predict(X_test)

            #errors in eV
            matrix[10*i + j,0] = metrics.mean_absolute_error(y_test, y_pred)
            matrix[10*i + j,1] = metrics.r2_score(y_test, y_pred)
            matrix[10*i + j,2] = rae(y_test, y_pred)
            matrix[10*i + j,3] = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

            matrix_fwhm[10*i + j,0] = metrics.mean_absolute_error(z_test, y_pred_fwhm)
            matrix_fwhm[10*i + j,1] = metrics.r2_score(z_test, y_pred_fwhm)
            matrix_fwhm[10*i + j,2] = rae(z_test, y_pred_fwhm)
            matrix_fwhm[10*i + j,3] = np.sqrt(metrics.mean_squared_error(z_test, y_pred_fwhm))

            matrix_cascade[10*i + j,0] = metrics.mean_absolute_error(z_test, y_pred_cascade)
            matrix_cascade[10*i + j,1] = metrics.r2_score(z_test, y_pred_cascade)
            matrix_cascade[10*i + j,2] = rae(z_test, y_pred_cascade)
            matrix_cascade[10*i + j,3] = np.sqrt(metrics.mean_squared_error(z_test, y_pred_cascade))

            #errors in nm
            #UNnormalize the data first
            y_test = y_test*(1239.84193/420 - 1239.84193/620)+1239.84193/620
            y_pred = y_pred*(1239.84193/420 - 1239.84193/620)+1239.84193/620
            z_test = z_test*(0.35)+0.05
            y_pred_fwhm = y_pred_fwhm*(0.35)+0.05
            y_pred_cascade = y_pred_cascade*(0.35)+0.05
            matrix[10*i + j,4] = metrics.mean_absolute_error(peak_eV_nm(y_test), peak_eV_nm(y_pred))
            matrix[10*i + j,5] = metrics.r2_score(peak_eV_nm(y_test), peak_eV_nm(y_pred))
            matrix[10*i + j,6] = rae(peak_eV_nm(y_test), peak_eV_nm(y_pred))
            matrix[10*i + j,7] = np.sqrt(metrics.mean_squared_error(peak_eV_nm(y_test), peak_eV_nm(y_pred)))
            matrix[10*i + j,8:13] = regressor_peak.coef_

            matrix_fwhm[10*i + j,4] = metrics.mean_absolute_error(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_fwhm))
            matrix_fwhm[10*i + j,5] = metrics.r2_score(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_fwhm))
            matrix_fwhm[10*i + j,6] = rae(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_fwhm))
            matrix_fwhm[10*i + j,7] = np.sqrt(metrics.mean_squared_error(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_fwhm)))
            matrix_fwhm[10*i + j,8:13] = regressor_fwhm.coef_

            matrix_cascade[10*i + j,4] = metrics.mean_absolute_error(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_cascade))
            matrix_cascade[10*i + j,5] = metrics.r2_score(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_cascade))
            matrix_cascade[10*i + j,6] = rae(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_cascade))
            matrix_cascade[10*i + j,7] = np.sqrt(metrics.mean_squared_error(FWHM_eV_nm(y_test,z_test), FWHM_eV_nm(y_pred,y_pred_cascade)))
            matrix_cascade[10*i + j,8:14] = regressor_cascade.coef_

            j+=1

    matrix_2 = np.zeros([1,21])
    matrix_2[0,:8] = matrix.mean(0)[:8]
    matrix_2[0,8:16] = np.std(matrix[:,:8], axis=0)
    matrix_2[0,16:21] = matrix.mean(0)[8:13]

    matrix_3 = np.zeros([1,21])
    matrix_3[0,:8] = matrix_fwhm.mean(0)[:8]
    matrix_3[0,8:16] = np.std(matrix_fwhm[:,:8], axis=0)
    matrix_3[0,16:21] = matrix_fwhm.mean(0)[8:13]

    matrix_4 = np.zeros([1,22])
    matrix_4[0,:8] = matrix_cascade.mean(0)[:8]
    matrix_4[0,8:16] = np.std(matrix_cascade[:,:8], axis=0)
    matrix_4[0,16:22] = matrix_cascade.mean(0)[8:14]

    print('\033[1m' + 'Absorption Peak' + '\033[0m')
    print("MAE (norm, eV):", matrix_2[0,0], matrix_2[0,8])
    print("R2 (norm, eV):", matrix_2[0,1], matrix_2[0,9])
    print("RAE (norm, eV):", matrix_2[0,2], matrix_2[0,10])
    print("RMSE (norm, eV):", matrix_2[0,3], matrix_2[0,11])
    print("Importances", matrix_2[0,8:13])
    print("MAE (nm):", matrix_2[0,4], matrix_2[0,12])
    print("R2 (nm):", matrix_2[0,5], matrix_2[0,13])
    print("RAE (nm):", matrix_2[0,6], matrix_2[0,14])
    print("RMSE (nm):", matrix_2[0,7], matrix_2[0,15])

    print('\033[1m' + 'Absorption FWHM (direct)' + '\033[0m')
    print("MAE (norm, eV):", matrix_3[0,0], matrix_3[0,8])
    print("R2 (norm, eV):", matrix_3[0,1], matrix_3[0,9])
    print("RAE (norm, eV):", matrix_3[0,2], matrix_3[0,10])
    print("RMSE (norm, eV):", matrix_3[0,3], matrix_3[0,11])
    print("Importances", matrix_3[0,8:13])
    print("MAE (nm):", matrix_3[0,4], matrix_3[0,12])
    print("R2 (nm):", matrix_3[0,5], matrix_3[0,13])
    print("RAE (nm):", matrix_3[0,6], matrix_3[0,14])
    print("RMSE (nm):", matrix_3[0,7], matrix_3[0,15])

    print('\033[1m' + 'Absorption FWHM (cascade)' + '\033[0m')
    print("MAE (norm, eV):", matrix_4[0,0], matrix_4[0,8])
    print("R2 (norm, eV):", matrix_4[0,1], matrix_4[0,9])
    print("RAE (norm, eV):", matrix_4[0,2], matrix_4[0,10])
    print("RMSE (norm, eV):", matrix_4[0,3], matrix_4[0,11])
    print("Importances", matrix_4[0,8:14])
    print("MAE (nm):", matrix_4[0,4], matrix_4[0,12])
    print("R2 (nm):", matrix_4[0,5], matrix_4[0,13])
    print("RAE (nm):", matrix_4[0,6], matrix_4[0,14])
    print("RMSE (nm):", matrix_4[0,7], matrix_4[0,15])

    return {'loss': matrix_3[0,3], 'status': STATUS_OK }

In [ ]:
rstate = np.random.default_rng(42)

from hyperopt import fmin, tpe, hp, STATUS_OK

best = fmin(L2_Reg,
            space=hp.uniform('x1', 0.001, 20),
            algo=tpe.suggest,
            max_evals=100,
            rstate=rstate)

print(best)

Absorption Peak                                                                                                
MAE (norm, eV):                                                                                                        
0.0283099593537675                                                                                                     
0.0031963339600243577                                                                                                  
R2 (norm, eV):                                                                                                         
0.9129413441114762                                                                                                     
0.023570092239699737                                                                                                   
RAE (norm, eV):                                                                                                        
0.24403351206115978                             

MAE (norm, eV):                                                                                                        
0.031261478446094844                                                                                                   
0.002582671644024355                                                                                                   
R2 (norm, eV):                                                                                                         
0.37591509630469583                                                                                                    
0.11482591197604496                                                                                                    
RAE (norm, eV):                                                                                                        
0.6825189108128848                                                                                                     
0.052062712597504446                    

0.02713108452431489                                                                                                    
0.0020883814378452243                                                                                                  
R2 (norm, eV):                                                                                                         
0.5150792437505858                                                                                                     
0.05007633683120889                                                                                                    
RAE (norm, eV):                                                                                                        
0.5918716853977006                                                                                                     
0.03539921387299666                                                                                                    
RMSE (norm, eV):                        

0.003132893092508648                                                                                                   
R2 (norm, eV):                                                                                                         
0.9323782770091349                                                                                                     
0.018471629466753587                                                                                                   
RAE (norm, eV):                                                                                                        
0.21324382887945564                                                                                                    
0.022369989745558823                                                                                                   
RMSE (norm, eV):                                                                                                       
0.0354791287616315                      

R2 (norm, eV):                                                                                                         
0.4838669457166967                                                                                                     
0.09086664014415365                                                                                                    
RAE (norm, eV):                                                                                                        
0.595730940845756                                                                                                      
0.051215129236553074                                                                                                   
RMSE (norm, eV):                                                                                                       
0.042013638536661686                                                                                                   
0.0030381781091947863                   

0.51385158709541                                                                                                       
0.10783914261633673                                                                                                    
RAE (norm, eV):                                                                                                        
0.5805269994649959                                                                                                     
0.05557444578215742                                                                                                    
RMSE (norm, eV):                                                                                                       
0.04074284480503026                                                                                                    
0.0038031965441287945                                                                                                  
Importances                             

0.06564516233518239                                                                                                    
RAE (norm, eV):                                                                                                        
0.37360052156831763                                                                                                    
0.06661925089763654                                                                                                    
RMSE (norm, eV):                                                                                                       
0.059418521957973716                                                                                                   
0.00819938460274708                                                                                                    
Importances                                                                                                            
[0.00716747 0.06564516 0.06661925 0.0081

RAE (norm, eV):                                                                                                        
0.5762285454888789                                                                                                     
0.05353248694547175                                                                                                    
RMSE (norm, eV):                                                                                                       
0.04115579510319683                                                                                                    
0.00395571730203485                                                                                                    
Importances                                                                                                            
[0.00250094 0.10164799 0.05353249 0.00395572 0.22215832 0.09796358]                                                    
MAE (nm):                               

0.7035422622777743                                                                                                     
0.0726949616007558                                                                                                     
RMSE (norm, eV):                                                                                                       
0.047315782488699575                                                                                                   
0.0060403205226525975                                                                                                  
Importances                                                                                                            
[0.00388078 0.13807744 0.07269496 0.00604032 0.30216394]                                                               
MAE (nm):                                                                                                              
3.1271470821522813                      

0.027472925957113516                                                                                                   
RMSE (norm, eV):                                                                                                       
0.040971588730727156                                                                                                   
0.005083350539856483                                                                                                   
Importances                                                                                                            
[0.00316193 0.02153042 0.02747293 0.00508335 0.65843159]                                                               
MAE (nm):                                                                                                              
6.381294680670381                                                                                                      
0.6584315899648623                      

RMSE (norm, eV):                                                                                                       
0.040143488743077646                                                                                                   
0.0037456937022714745                                                                                                  
Importances                                                                                                            
[0.0025776  0.08508961 0.05502836 0.00374569 0.18896869 0.07671803]                                                    
MAE (nm):                                                                                                              
2.2754362249762603                                                                                                     
0.18896869483111106                                                                                                    
R2 (nm):                                

0.045249542304451676                                                                                                   
0.004397923074185704                                                                                                   
Importances                                                                                                            
[0.00335339 0.10219865 0.06128799 0.00439792 0.33184235]                                                               
MAE (nm):                                                                                                              
2.94768917073913                                                                                                       
0.3318423500519812                                                                                                     
R2 (nm):                                                                                                               
0.43511452266794953                     

0.005676024078568558                                                                                                   
Importances                                                                                                            
[0.00347833 0.01647781 0.02247715 0.00567602 0.71480287]                                                               
MAE (nm):                                                                                                              
5.328820333623653                                                                                                      
0.7148028660871272                                                                                                     
R2 (nm):                                                                                                               
0.9378774658485136                                                                                                     
0.015905931400537903                    

Importances                                                                                                            
[0.00197656 0.07590225 0.04578424 0.00264107 0.13933266 0.08260291]                                                    
MAE (nm):                                                                                                              
2.2084771370787757                                                                                                     
0.13933266103365896                                                                                                    
R2 (nm):                                                                                                               
0.6304612429744189                                                                                                     
0.08260290596100989                                                                                                    
RAE (nm):                               

[0.00319505 0.13169218 0.06181143 0.00528987 0.24869067]                                                               
MAE (nm):                                                                                                              
2.4274771916774713                                                                                                     
0.24869067479576504                                                                                                    
R2 (nm):                                                                                                               
0.5527683178402982                                                                                                     
0.09818213094271204                                                                                                    
RAE (nm):                                                                                                              
0.5604236394575077                      

MAE (nm):                                                                                                              
6.196089145863939                                                                                                      
0.730719980169361                                                                                                      
R2 (nm):                                                                                                               
0.9171595938154395                                                                                                     
0.020984370844607567                                                                                                   
RAE (nm):                                                                                                              
0.2398835810262173                                                                                                     
0.029596960625870562                    

2.5480229485172172                                                                                                     
0.3375186194549482                                                                                                     
R2 (nm):                                                                                                               
0.4990175422408482                                                                                                     
0.14149232922980765                                                                                                    
RAE (nm):                                                                                                              
0.5875784320801793                                                                                                     
0.05947525636741447                                                                                                    
RMSE (nm):                              

0.18475325173752463                                                                                                    
R2 (nm):                                                                                                               
0.583370808334135                                                                                                      
0.08636766795671195                                                                                                    
RAE (nm):                                                                                                              
0.5562820262346644                                                                                                     
0.041238710537416415                                                                                                   
RMSE (nm):                                                                                                             
3.5830662005949705                      

R2 (nm):                                                                                                               
0.9183335323180188                                                                                                     
0.02131846181394074                                                                                                    
RAE (nm):                                                                                                              
0.23757842576283866                                                                                                    
0.028141934404059505                                                                                                   
RMSE (nm):                                                                                                             
8.577225324629103                                                                                                      
1.093440669792656                       

0.5887229798912073                                                                                                     
0.06845344682326307                                                                                                    
RAE (nm):                                                                                                              
0.5526678596839337                                                                                                     
0.0409336285574521                                                                                                     
RMSE (nm):                                                                                                             
3.56888656652579                                                                                                       
0.24782870758456044                                                                                                    
Absorption Peak                         

0.09116875041599512                                                                                                    
RAE (nm):                                                                                                              
0.5964522944704918                                                                                                     
0.044807065635156934                                                                                                   
RMSE (nm):                                                                                                             
3.794166581033042                                                                                                      
0.2864881397148337                                                                                                     
Absorption FWHM (cascade)                                                                                      
MAE (norm, eV):                                 

RAE (nm):                                                                                                              
0.2413360458965846                                                                                                     
0.028172354576849804                                                                                                   
RMSE (nm):                                                                                                             
8.601437156719612                                                                                                      
1.0376546792661527                                                                                                     
Absorption FWHM (direct)                                                                                       
MAE (norm, eV):                                                                                                        
0.027245251955244527                            

0.5601145058276712                                                                                                     
0.0326449772261424                                                                                                     
RMSE (nm):                                                                                                             
3.683501407130671                                                                                                      
0.3514841731309609                                                                                                     
Absorption Peak                                                                                                
MAE (norm, eV):                                                                                                        
0.02462675246067489                                                                                                    
0.0032025755949381396                           

0.05037849548172306                                                                                                    
RMSE (nm):                                                                                                             
3.6940430105097                                                                                                        
0.3695521212747305                                                                                                     
Absorption FWHM (cascade)                                                                                      
MAE (norm, eV):                                                                                                        
0.02519186797376848                                                                                                    
0.002106606760076049                                                                                                   
R2 (norm, eV):                                  

RMSE (nm):                                                                                                             
7.84960535427769                                                                                                       
1.1803292556517382                                                                                                     
Absorption FWHM (direct)                                                                                       
MAE (norm, eV):                                                                                                        
0.026947682183946463                                                                                                   
0.0029607615979973735                                                                                                  
R2 (norm, eV):                                                                                                         
0.5170958006943996                              

3.587645796358717                                                                                                      
0.3492036302750978                                                                                                     
Absorption Peak                                                                                                
MAE (norm, eV):                                                                                                        
0.02696666544087551                                                                                                    
0.0033153728222289733                                                                                                  
R2 (norm, eV):                                                                                                         
0.9220552725302014                                                                                                     
0.019193709729086125                            

0.45524783519492895                                                                                                    
Absorption FWHM (cascade)                                                                                      
MAE (norm, eV):                                                                                                        
0.029423470375436418                                                                                                   
0.003161609425836811                                                                                                   
R2 (norm, eV):                                                                                                         
0.41103763855939707                                                                                                    
0.07869760349623683                                                                                                    
RAE (norm, eV):                                 

Absorption FWHM (direct)                                                                                       
MAE (norm, eV):                                                                                                        
0.026686538152445455                                                                                                   
0.002230454412184808                                                                                                   
R2 (norm, eV):                                                                                                         
0.5070529698062484                                                                                                     
0.10704898206532198                                                                                                    
RAE (norm, eV):                                                                                                        
0.5836320475050606                              

MAE (norm, eV):                                                                                                        
0.025880181558907246                                                                                                   
0.0031719489860623294                                                                                                  
R2 (norm, eV):                                                                                                         
0.9266809328947341                                                                                                     
0.023181337674764005                                                                                                   
RAE (norm, eV):                                                                                                        
0.2228973912387969                                                                                                     
0.027173263494672334                    

0.025299289837143107                                                                                                   
0.0024441924638861252                                                                                                  
R2 (norm, eV):                                                                                                         
0.5431650444587072                                                                                                     
0.10013145521513574                                                                                                    
RAE (norm, eV):                                                                                                        
0.5527141554118096                                                                                                     
0.05595037172462042                                                                                                    
RMSE (norm, eV):                        

0.002517252528398005                                                                                                   
R2 (norm, eV):                                                                                                         
0.4039447014926069                                                                                                     
0.12397218529455342                                                                                                    
RAE (norm, eV):                                                                                                        
0.6559669602846323                                                                                                     
0.0545722260699538                                                                                                     
RMSE (norm, eV):                                                                                                       
0.04516592796557451                     

R2 (norm, eV):                                                                                                         
0.9399560417650369                                                                                                     
0.016590234088358448                                                                                                   
RAE (norm, eV):                                                                                                        
0.20428567808960058                                                                                                    
0.022764678247251247                                                                                                   
RMSE (norm, eV):                                                                                                       
0.033398794329335305                                                                                                   
0.004745793391944666                    

0.48850510953406107                                                                                                    
0.09323375075023609                                                                                                    
RAE (norm, eV):                                                                                                        
0.5825223355874438                                                                                                     
0.04619808558998185                                                                                                    
RMSE (norm, eV):                                                                                                       
0.04194253059455189                                                                                                    
0.004513753118492477                                                                                                   
Importances                             

0.12206700813020324                                                                                                    
RAE (norm, eV):                                                                                                        
0.5961480368865474                                                                                                     
0.06853156586983958                                                                                                    
RMSE (norm, eV):                                                                                                       
0.0416560883884352                                                                                                     
0.0053574077258393684                                                                                                  
Importances                                                                                                            
[0.00372114 0.12206701 0.06853157 0.0053

RAE (norm, eV):                                                                                                        
0.2861782347218997                                                                                                     
0.0396361547226462                                                                                                     
RMSE (norm, eV):                                                                                                       
0.047608155500005175                                                                                                   
0.010633847584698443                                                                                                   
Importances                                                                                                            
[0.00627431 0.04079855 0.03963615 0.01063385 1.30429756]                                                               
MAE (nm):                               

0.5940760130719629                                                                                                     
0.06344083508385254                                                                                                    
RMSE (norm, eV):                                                                                                       
0.042751769817167135                                                                                                   
0.005282563095499049                                                                                                   
Importances                                                                                                            
[0.00352508 0.1234681  0.06344084 0.00528256 0.26948414 0.08766923]                                                    
MAE (nm):                                                                                                              
2.4697150953671225                      

0.06702255842290822                                                                                                    
RMSE (norm, eV):                                                                                                       
0.042162264988386315                                                                                                   
0.005677722081438107                                                                                                   
Importances                                                                                                            
[0.00358676 0.13397641 0.06702256 0.00567772 0.27155792]                                                               
MAE (nm):                                                                                                              
2.4182362522494842                                                                                                     
0.2715579204472229                      

RMSE (norm, eV):                                                                                                       
0.037271046228354664                                                                                                   
0.006678880299869334                                                                                                   
Importances                                                                                                            
[0.00455814 0.01923684 0.02688236 0.00667888 0.88607134]                                                               
MAE (nm):                                                                                                              
5.785252061706982                                                                                                      
0.8860713353414915                                                                                                     
R2 (nm):                                

0.04954670304741909                                                                                                    
0.0044716805900658                                                                                                     
Importances                                                                                                            
[0.00345776 0.08153725 0.05109932 0.00447168 0.26314812 0.10130789]                                                    
MAE (nm):                                                                                                              
3.2694507076121253                                                                                                     
0.26314811834823554                                                                                                    
R2 (nm):                                                                                                               
0.2921721706248957                      

0.0032230538225429236                                                                                                  
Importances                                                                                                            
[0.00200746 0.08604545 0.0376247  0.00322305 0.15650691]                                                               
MAE (nm):                                                                                                              
2.375318665861516                                                                                                      
0.15650691421784244                                                                                                    
R2 (nm):                                                                                                               
0.5912765361517299                                                                                                     
0.08129274908999733                     